/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/components/shared/AboutView.vue')['default']
    Button: typeof import('./src/components/shared/Button.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeView: typeof import('./src/components/shared/HomeView.vue')['default']
    IngreseConApple: typeof import('./src/components/login/IngreseConApple.vue')['default']
    IngreseConFacebook: typeof import('./src/components/login/IngreseConFacebook.vue')['default']
    IngreseConGoolge: typeof import('./src/components/login/IngreseConGoolge.vue')['default']
    InputTexto: typeof import('./src/components/shared/InputTexto.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/home/sidebar.vue')['default']
  }
}
